name: 'Terraform Plan'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Использовать оболочку Bash, независимо от того, является ли GitHub Actions runner ubuntu-latest, macos-latest или windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Проверка репозитория на GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Установка последней версии Terraform CLI и настройка файла конфигурации Terraform CLI с помощью токена пользователя Terraform Cloud
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Инициализация новой или существующей рабочей директории Terraform, создание начальных файлов, загрузка удаленного состояния, загрузка модулей и т.д.
    - name: Terraform Init
      run: terraform init

    # Проверка соответствия всех файлов конфигурации Terraform каноническому формату
    - name: Terraform Format
      run: terraform fmt -check

    # Генерация плана выполнения для Terraform
    - name: Terraform Plan
      run: terraform plan -input=false

